[package]
name = "serde"
version = "3.4.0"
description = "A serialisation and deserialisation library for Motoko."
repository = "https://github.com/NatLabs/serde"
keywords = ["json", "candid", "cbor", "urlencoded", "serialization"]
license = "MIT"

[dependencies]
core = "2.0.0"
"itertools@0.2.2" = "0.2.2"
"xtended-numbers" = "2.3.0"
"xtended-numbers@2.3.0" = "2.3.0" # because for ByteUtils
"cbor@4.1.0" = "4.1.0"
"sha2@0.1.6" = "0.1.6"
"byte-utils@0.1.2" = "https://github.com/ggreif/ByteUtils#fc522a0ba56764b76b866e29d3cbeeb3ea7f0060"
buffer = "0.1.0"
"base@0.14.13" = "0.14.13" # because for ByteUtils
"base@0.7.3" = "0.14.13" # because for ByteUtils

[dev-dependencies]
test = "2.1.1"
fuzz = "1.0.0"
rep-indy-hash = "0.1.1"
candid = "2.4.2"
bench = "1.0.0"

[toolchain]
wasmtime = "33.0.1"
moc = "1.1.0"
