[package]
name = "serde-core"
version = "0.1.2"
description = "A serialisation and deserialisation library for Motoko."
repository = "https://github.com/NatLabs/serde"
keywords = [ "json", "candid", "cbor", "urlencoded", "serialization" ]
license = "MIT"

[dependencies]
"base@0.16" = "0.16.0"
"itertools@0.2.2" = "0.2.2"
"xtended-numbers@2.3" = "2.3.0"
"cbor@4.1" = "4.1.0"
"map@9.0" = "9.0.1"
"sha2@0.1" = "0.1.14"
"byte-utils@0.2" = "0.2.0"
"core@2.4" = "2.4.0"

[dev-dependencies]
test = "2.1.2"
fuzz = "1.0.0"
rep-indy-hash = "0.2.1"
candid = "2.4.2"
bench = "2.0.1"

[toolchain]
wasmtime = "43.0.0"
moc = "1.4.1"
