name: Makefile CI

on:
    push:
        branches: ["main", "actions"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: aviate-labs/setup-dfx@v0.2.3
              with:
                vessel-version: 0.6.3
                dfx-version: 0.12.1

            - name: "install mops"
              run: |
                  git clone https://github.com/ZenVoich/mops
                  cd mops/cli
                  npm i
                  echo -e "#!/usr/bin/env node\n$(cat ./cli.js)" > .cli.js
                  # echo "alias mops=node $(pwd)/cli.js" >> ~/.bashrc 
                  # source ~/.bashrc 
                  chmod +x ./cli.js
                  ln -s ./cli.js /usr/local/bin/mops
                  ls /usr/local/bin
                  mops i
                  mops sources


            - name: Detect Warnings
              run: make no-warn

            - name: Run Tests
              run: make test

            - name: Generate Docs
              run: make docs
